### ISSUE TITLE
`basissets` and `pseudos` keys are always present in the cp2k calculation builder.

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-cp2k#113]
`basissets` and `pseudos` are defined as optional namespaces so we were assuming that they shouldn't be present in the inputs. However, the freshly created builder already contains both of them as empty dictionaries.

This causes the following if statements to be always executed:
https://github.com/aiidateam/aiida-cp2k/blob/0c3c3aad8f1a0151018ce8542fe218c96c37e66c/aiida_cp2k/calculations/__init__.py#L154

and

https://github.com/aiidateam/aiida-cp2k/blob/0c3c3aad8f1a0151018ce8542fe218c96c37e66c/aiida_cp2k/calculations/__init__.py#L159

@dev-zero would you be able to have a look? This is rather urgent as the 'normal' functionality is broken.

**Comment by yakutovicha** [comment]
proof:
![Screen Shot 2020-09-23 at 12 04 43 PM](https://user-images.githubusercontent.com/13118485/93998551-0095e780-fd95-11ea-9bdc-6248a6a7fd14.png)

**Comment by dev-zero** [comment]
I wonder how other plugins are handling this (e.g. QE seems to have a lot of similar optional ports guarded by conditionals when prepping a calculation). The quickfix is probably doing something like `if 'pseudos' in self.inputs and self.inputs.pseudos` (test needed), but in the end this seems to be a bug in the ProcessBuilderNamespace.

**Comment by dev-zero** [comment]
... and we have to figure out why `examples/single_calculations/example_dft.py::example_dft` succeeds without the `aiida-gaussian-datatypes` being installed, since it also uses `get_builder()`

**Comment by yakutovicha** [comment]
I talked to @sphuber and he said that there was such a bug in the `aiida-core`, but it got fixed. So quite probably we have to do nothing except of updating it.

I will try to make a small example to reproduce the problem, and we can then proceed further.

**Comment by yakutovicha** [comment]
Ok, so I found the origin of the problem. Luckily it has nothing to do with `aiida-cp2k` or `aiida-core`. However, it has to do with the way we submit the calculation using `SubmitButtonWidget` in AiiDAlab. 

Essentially, the problem boils down to [the way](https://github.com/aiidalab/aiidalab-widgets-base/blob/develop/aiidalab_widgets_base/process.py#L94-L102). More specifically to this:

```python
process = submit(process_class, **builder)
```

So when the builder, that contains empty basis sets and pseudos, gets unpacked - it contains basis sets and pseudos (even though) they are empty. The reason I did things this way is because I wanted users to be able to provide both: input dictionary or input builder.

Now I have a question (more to @sphuber) how to proceed further. Should I modify the `SubmitButtonWidget`, so that it distinguishes builder and dictionary? Or should we implement some `get_dict()` method to the input builder which would be able to provide a valid input dictionary?

**Comment by sphuber** [comment]
The `submit` method is already written to support a `ProcessBuilder` directly. All you have to do is change that line to:
```
process = submit(builder)
```
and it will work as you intended it.

**Comment by yakutovicha** [comment]
> The submit method is already written to support a ProcessBuilder directly.

This I know, see my text above:

> The reason I did things this way is because I wanted users to be able to provide both: either input dictionary or input builder.

Essentially, the question here is: are we moving away from using dictionaries as the input to the submit method? Should I drop support of using dictionaries in the  `SubmitButtonWidget`, or should I changes its API two support both in the following way:

```python
SubmitButtonWidget(process_class, input_dictionary=None, input_builder=None)
```

**Comment by sphuber** [comment]
I looked at the code that you linked and I am not sure how it is supposed to work, but is it that whatever callable is defined for `input_dictionary_function` should be able to return either the dictionary of inputs, or a `ProcessBuilder` instance? If that is the case, then you could just simply use some type checking to make it work, similar to what the `submit` implementation does in `aiida-core`:
```
input_dict = self.input_dictionary_function()
if isinstance(input_dict, ProcessBuilder):
    builder = input_dict
    process_class = builder.process_class
    input_dict.update(**builder._inputs(prune=True))  # pylint: disable=protected-access
```

Finally, in this case, maybe I would consider renaming `input_dictionary_function` if it really is also supposed to be able to return a builder.

> Essentially, the question here is: are we moving away from using dictionaries as the input to the submit method?

No, both are perfectly fine and will be kept. The builder was added mostly to provide additional functionality in interactive modes, such as a shell or notebook. But we also wanted it to be useful in static code such as scripts, so we added support for it in the launcher methods.

**Comment by yakutovicha** [comment]
> I looked at the code that you linked and I am not sure how it is supposed to work, but is it that whatever callable is defined for `input_dictionary_function` should be able to return either the dictionary of inputs, or a `ProcessBuilder` instance?

Yes, that was the intension.

> Why don't you just mirror the exact same signature of `submit` in your `SubmitButtonWidget`?
> You can just do:
> 
> ```
> SubmitButtonWidget(process, **inputs)
> ```
> 
> and then you literally just forward this to `aiida.engine.submit`. Users can then do `SubmitButtonWidget(builder)` as well as `SubmitButtonWidget(PwBaseWorkChain, **{'code': ...})`. I don't see why you would need or want a different interface

It is not really possible, as `SubmitButtonWidget` is a widget in the first place. So it has to be created and shown before any other input generation code is executed. Therefore, we perform the generation of inputs through the `input_dictionary_function`  function. 

> Finally, in this case, maybe I would consider renaming `input_dictionary_function` if it really is also supposed to be able to return a builder.

Yes, I will do that.
