### ISSUE TITLE
Tests fail with import error in sqlalchemy

### ISSUE THREAD

**Issue by oschuett** [aiidateam/aiida-cp2k#129]
Recently, the aiida-cp2k dashboard test started [failing](https://dashboard.cp2k.org/archive/aiida/index.html):
```
ImportError: cannot import name '_literal_as_text' from 'sqlalchemy.sql.expression' (/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/expression.py)
```

**Comment by oschuett** [comment]
Interestingly, it [recovered](https://dashboard.cp2k.org/archive/aiida/commit_27588553a701cf8a68abf65255643b9878d22bbe.txt) today. I guess, because `sqlalchemy-utils` went from version `0.34.2` to `0.36.0`.

**Comment by yakutovicha** [comment]
I like very much this self-closing issues :D
