### ISSUE TITLE
AiiDA-CP2K does not work with Python 3.10

### ISSUE THREAD

**Issue by oschuett** [aiidateam/aiida-cp2k#158]
Ubuntu 22.04 upgraded to Python 3.10, which in turn no longer supports `collections.Mapping` and thereby breaks [the tests](https://storage.googleapis.com/cp2k-ci/run-cp2k-aiida-7fb0a63f_report.txt).

https://github.com/aiidateam/aiida-cp2k/blob/0916da4d53ed056a84e25de5e8691841ee23bbab/aiida_cp2k/utils/workchains.py#L32

**Comment by yakutovicha** [comment]
I will take care of that within the incoming days. Sorry, I can't work on that immediately.
