### ISSUE TITLE
Removal of version numbers from development branch

### ISSUE THREAD

**Issue by oschuett** [aiidateam/aiida-cp2k#163]
We stopped assigning version numbers to the development branch (https://github.com/cp2k/cp2k/pull/2188). As a result the [dashboard test](https://dashboard.cp2k.org/archive/aiida/index.html) is now failing.

**Comment by yakutovicha** [comment]
Thanks for the report, @oschuett. May I ask, why is it necessary? Having a version in the output is convenient. Moreover, some parts of the plugin rely on that.

**Comment by yakutovicha** [comment]
> > Moreover, some parts of the plugin rely on that.
> 
> How exactly do they depend on the version string? Maybe we can find a better solution?

Of course, I would very much prefer to have something like this: https://github.com/cp2k/cp2k/issues/215. But I am not sure it is going to happen.

**Comment by yakutovicha** [comment]
> Then the existing parser should continue to work:

very much in favour of this! Thanks a lot!
