### ISSUE TITLE
Use of _DEFAULT_FILE in calculatons

### ISSUE THREAD

**Issue by bosonie** [aiidateam/aiida-cp2k#21]
As discussed in the plugin-migration slack, I think it is incorrect to use the _DEFAULT_FILE string if you defined also the file in spec.input. When in spec.input, the string is exposed to modification from the user and one should use its real value in the rest of the code, not the default value.
For instance
calcinfo.stdin_name = self._DEFAULT_INPUT_FILE
should be:
calcinfo.stdin_name = self.inputs.metadata.options.input_filename

**Comment by yakutovicha** [comment]
Thanks @bosonie for pointing this out.

Essentially the choice between using constants or `spec.input(specifying input filename here)` is dictated whether you want to keep the input filename constant or you may want to modify it.

We are discussing this now with other people, but most probably we do NOT want to allow users to modify the input filename. Therefore, we will just delete corresponding  `spec.input()` functions.
