### ISSUE TITLE
Calculation and Parser compatibility with AiiDA 1.0.0b4

### ISSUE THREAD

**Issue by pzarabadip** [aiidateam/aiida-cp2k#27]
```
Calculation
```
The current version fails in retrieving the relaxed structure of test_geopt.py. 
The solution that I came up with is modifying the following part of the code:
https://github.com/aiidateam/aiida-cp2k/blob/27f5e075ddf2f1badaa5523a487339f8ed7711b1/aiida_cp2k/calculations/__init__.py#L68

to : 
```python
        spec.output('output_structure', valid_type=StructureData, required=False, help='relaxed structure')
```

```
Parser
```
It seems the following part of the code:
https://github.com/aiidateam/aiida-cp2k/blob/27f5e075ddf2f1badaa5523a487339f8ed7711b1/aiida_cp2k/parsers/__init__.py#L56

needs to be changed to:
```python
        fname = self.node.process_class._DEFAULT_OUTPUT_FILE
```
Also, here:
https://github.com/aiidateam/aiida-cp2k/blob/27f5e075ddf2f1badaa5523a487339f8ed7711b1/aiida_cp2k/parsers/__init__.py#L127

**Comment by yakutovicha** [comment]
Thanks @pzarabadip.

All done and the new version of the plugin (1.0.0b2) is released
