### ISSUE TITLE
Dashboard test failing

### ISSUE THREAD

**Issue by oschuett** [aiidateam/aiida-cp2k#29]
After 4ae956be6293fb1e28d13aba0e768d121787cab3 the [dasboard test](https://dashboard.cp2k.org/archive/aiida/commit_cc9b192f29c31358703847cafee6136a05c3293a.txt) started failing. I'm not sure if this should be fixed on the aiida-cp2k or the [cp2k side](https://github.com/cp2k/cp2k/blob/master/tools/docker/Dockerfile.test_aiida).

**Comment by yakutovicha** [comment]
Hi Ole,

Looks like it is enough to just replace [this line](https://github.com/cp2k/cp2k/blob/cc9b192f29c31358703847cafee6136a05c3293a/tools/docker/scripts/test_aiida.sh#L23) with:
```
pip install --quiet ./aiida-cp2k/[pre-commit,test]
```

**Comment by oschuett** [comment]
Thanks! Let's give it a try: https://github.com/cp2k/cp2k/pull/454.

**Comment by yakutovicha** [comment]
Looks like this [workaround](https://github.com/cp2k/cp2k/blob/cc9b192f29c31358703847cafee6136a05c3293a/tools/docker/scripts/test_aiida.sh#L26) is not needed anymore

**Comment by oschuett** [comment]
Still failing: https://storage.googleapis.com/cp2k-ci/run-cp2k-aiida-52f0836a_report.txt

**Comment by yakutovicha** [comment]
> Still failing: https://storage.googleapis.com/cp2k-ci/run-cp2k-aiida-52f0836a_report.txt

yes, we my previous post

**Comment by yakutovicha** [comment]
Bingo, it worked!

**Comment by oschuett** [comment]
Indeed :-) Thanks for the quick help!
