### ISSUE TITLE
Prospector failing in cp2k-ci

### ISSUE THREAD

**Issue by oschuett** [aiidateam/aiida-cp2k#56]
While prospector passes in the [TravisCI](https://travis-ci.org/aiidateam/aiida-cp2k/builds/599973450#L646) it fails in the [cp2k-ci](https://dashboard.cp2k.org/archive/aiida/commit_dd13ebccf1c523705b7bcbb85af0fd06f4ac1fd7.txt). Any ideas?

**Comment by yakutovicha** [comment]
I think it is related to py2 vs py3 compatibility. On travis we are testing against py3 and we have `pylint=2.3.1`, while you are testing against py2 and you have `pylint=1.9.4` ([see here](https://github.com/aiidateam/aiida-cp2k/blob/ea5cd54bd8419fefd24967f2c2569031cc28a592/setup.json#L47-L48)).

If I make a new PR with fixing the problems would you be able to test it?

**Comment by oschuett** [comment]
I think, in that I case I'd rather convert the [cp2k-ci test](https://github.com/cp2k/cp2k/blob/master/tools/docker/scripts/install_aiida.sh) to Python3 instead.

**Comment by yakutovicha** [comment]
Sure. In case you need inspiration, check the [aiida-docker-base](https://github.com/aiidateam/aiida-docker-base/blob/develop/Dockerfile) container.

**Comment by oschuett** [comment]
Hmm, now I'm getting:
```
$git clone https://github.com/aiidateam/aiida-cp2k.git
Cloning into 'aiida-cp2k'...

$pip3 install './aiida-cp2k/[pre-commit,test]'
Processing ./aiida-cp2k
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-2hdnlhpq-build/setup.py", line 27, in <module>
        run_setup()
      File "/tmp/pip-2hdnlhpq-build/setup.py", line 18, in run_setup
        kwargs = json.load(info)
      File "/usr/lib/python3.6/json/__init__.py", line 296, in load
        return loads(fp.read(),
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 160: ordinal not in range(128)
```
