### ISSUE TITLE
FileNotFoundError: multistage_protocols/test.yaml

### ISSUE THREAD

**Issue by oschuett** [aiidateam/aiida-cp2k#59]
I'm sorry to bother you again. The aiida-cp2k test on the dashboard is [failing again](https://dashboard.cp2k.org/archive/aiida/index.html). This time it also happens with [Python3](https://github.com/cp2k/cp2k/pull/602/checks). So, what am I doing differently that the TravisCI?

The full error message is:
```
Testing CP2K ENERGY on H2O (DFT) through a workchain...
Submitted calculation...
11/03/2019 08:30:08 PM <96016> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [89|Cp2kMultistageWorkChain|on_except]: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/plumpy/process_states.py", line 220, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/aiida/engine/processes/workchains/workchain.py", line 165, in run
    return self._do_step()
  File "/usr/local/lib/python3.6/dist-packages/aiida/engine/processes/workchains/workchain.py", line 181, in _do_step
    finished, stepper_result = self._stepper.step()
  File "/usr/local/lib/python3.6/dist-packages/plumpy/workchains.py", line 283, in step
    finished, result = self._child_stepper.step()
  File "/usr/local/lib/python3.6/dist-packages/plumpy/workchains.py", line 234, in step
    return True, self._fn(self._workchain)
  File "/usr/local/lib/python3.6/dist-packages/aiida_cp2k/workchains/multistage.py", line 204, in setup_multistage
    with open(yamlfullpath, 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/aiida_cp2k/workchains/multistage_protocols/test.yaml'

```

**Comment by yakutovicha** [comment]
This is completely my fault. I didn't know that to properly include the files located inside `/aiida_cp2k/workchains/multistage_protocols` I had to add them explicitly in MANIFEST.in 

Even more surprising to me is why this line worked fine than
https://github.com/aiidateam/aiida-cp2k/blob/60d39d1bdf857febaf1a3856d1c59f13698cb598/Dockerfile#L27

Is it because of the `--user` option? Do you know?

**Comment by yakutovicha** [comment]
@oschuett please reopen if the issue persists.

**Comment by yakutovicha** [comment]
@oschuett please also take a note on how we currently run tests. It is now enough to just call pytest:

https://github.com/aiidateam/aiida-cp2k/blob/66ab9b4d72c0cfd0950fb7f464c874529dd73190/.travis.yml#L16-L17

**Comment by oschuett** [comment]
Thanks a lot! I updated the cp2k test accordingly: https://github.com/cp2k/cp2k/commit/dbebbfc6f35301f8440f150e09e16c1399123730
