### ISSUE TITLE
Exception when use dry_run

### ISSUE THREAD

**Issue by xjf729** [aiidateam/aiida-cp2k#98]
aiida-core version: 1.0.1
aiida-cp2k version: 1.0.0b6

I want to apply a submit test to generate a folder named `submit_test` without submitting process to remote scheduler. However, when I set as follows, it raises "aiida.common.exceptions.InvalidOperation: cannot submit a process from within another with `dry_run=True`"

```python
Cp2kBaseWorkChain = WorkflowFactory('cp2k.base')
builder = Cp2kBaseWorkChain.get_builder()
# skip other builder.cp2k settings
builder.cp2k.metadata.dry_run = True
run(builder)
```

However, when I set set follows, nothing is wrong

```python
Cp2kCalculation = CalculationFactory('cp2k')
builder = Cp2kCalculation.get_builder()
# skip other builder settings
builder.metadata.dry_run = True
run(builder)
```

**Comment by yakutovicha** [comment]
Can you help me to understand why would you need to submit a dry run calculation from a work chain that is run normally? 

In addition to that, It seems not to be possible to submit the work chain itself for a dry run. And that looks OK to me because it cannot be generalized. Workchains are supposed to deal with the outputs of calculations submitted by it. If there are no outputs produced - work chain cannot proceed normally.

So I think such a behaviour is totally normal and expected.

**Comment by xjf729** [comment]
You are right, we don't need dry_run in most cases.

Actually, I use dry_run to wonder if the generated input files are correct. If I use `run/submit` directly without dry_run, the jobs will be submitted to the remote servers, although I can use ssh to remote servers to check the input files.

**Comment by yakutovicha** [comment]
> You are right, we don't need dry_run in most cases.
> 
> Actually, I use dry_run to wonder if the generated input files are correct. If I use `run/submit` directly without dry_run, the jobs will be submitted to the remote servers, although I can use ssh to remote servers to check the input files.

Sorry, I guess I wasn't very clear. My point here was that (I think) it is fundamentally not possible to allow dry submissions from a work chain. Imagine a situation: work chain submits calculation `A` which returns a result `RA`. This result is further used as an input for the calculation `B`. If you do dru run, there is simply no `RA`, so `B` can't even start.

**Comment by xjf729** [comment]
Though we cannot get the `RA` and the input of `B`, if there are some methods to get the input of `A` the first step in work chain.

**Comment by yakutovicha** [comment]
> Though we cannot get the `RA` and the input of `B`, if there are some methods to get the input of `A` the first step in work chain.

I believe this is not possible, as from work chain point of view `A` is just the same step as `B`, so I doubt it is possible. But  I will double-check.

**Comment by yakutovicha** [comment]
okay, so I got the confirmation. Those two things are not allowed by `aiida-core`:
* dry run of work chains.
* dry run of subprocesses

**Comment by yakutovicha** [comment]
aiida-cp2k can't do anything about it, so I close the issue.
